Sabrina Herman_202331241

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import Library yang akan digunakan 

In [6]:
dataset = pd.read_csv('bank_customer.csv', sep = ';')
dataset


age           job   marital  education default  balance housing loan  \
0       58    management   married   tertiary      no     2143     yes   no   
1       44    technician    single  secondary      no       29     yes   no   
2       33  entrepreneur   married  secondary      no        2     yes  yes   
3       47   blue-collar   married    unknown      no     1506     yes   no   
4       33       unknown    single    unknown      no        1      no   no   
...    ...           ...       ...        ...     ...      ...     ...  ...   
45206   51    technician   married   tertiary      no      825      no   no   
45207   71       retired  divorced    primary      no     1729      no   no   
45208   72       retired   married  secondary      no     5715      no   no   
45209   57   blue-collar   married  secondary      no      668      no   no   
45210   37  entrepreneur   married  secondary      no     2971      no   no   

         contact  day month  duration  campaign  pdays  previous poutcome    y  
0        unknown    5   may       261         1     -1         0  unknown   no  
1        unknown    5   may       151         1     -1         0  unknown   no  
2        unknown    5   may        76         1     -1         0  unknown   no  
3        unknown    5   may        92         1     -1         0  unknown   no  
4        unknown    5   may       198         1     -1         0  unknown   no  
...          ...  ...   ...       ...       ...    ...       ...      ...  ...  
45206   cellular   17   nov       977         3     -1         0  unknown  yes  
45207   cellular   17   nov       456         2     -1         0  unknown  yes  
45208   cellular   17   nov      1127         5    184         3  success  yes  
45209  telephone   17   nov       508         4     -1         0  unknown   no  
45210   cellular   17   nov       361         2    188        11    other   no  

[45211 rows x 17 columns]

membaca dataset

In [8]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   age        45211 non-null  int64 
 1   job        45211 non-null  object
 2   marital    45211 non-null  object
 3   education  45211 non-null  object
 4   default    45211 non-null  object
 5   balance    45211 non-null  int64 
 6   housing    45211 non-null  object
 7   loan       45211 non-null  object
 8   contact    45211 non-null  object
 9   day        45211 non-null  int64 
 10  month      45211 non-null  object
 11  duration   45211 non-null  int64 
 12  campaign   45211 non-null  int64 
 13  pdays      45211 non-null  int64 
 14  previous   45211 non-null  int64 
 15  poutcome   45211 non-null  object
 16  y          45211 non-null  object
dtypes: int64(7), object(10)
memory usage: 5.9+ MB


informasi dataset

In [10]:
categorical_features = [feature for feature in dataset.columns
                        if dataset[feature].dtypes == "O"]
dataset[categorical_features]

job   marital  education default housing loan    contact  \
0        management   married   tertiary      no     yes   no    unknown   
1        technician    single  secondary      no     yes   no    unknown   
2      entrepreneur   married  secondary      no     yes  yes    unknown   
3       blue-collar   married    unknown      no     yes   no    unknown   
4           unknown    single    unknown      no      no   no    unknown   
...             ...       ...        ...     ...     ...  ...        ...   
45206    technician   married   tertiary      no      no   no   cellular   
45207       retired  divorced    primary      no      no   no   cellular   
45208       retired   married  secondary      no      no   no   cellular   
45209   blue-collar   married  secondary      no      no   no  telephone   
45210  entrepreneur   married  secondary      no      no   no   cellular   

      month poutcome    y  
0       may  unknown   no  
1       may  unknown   no  
2       may  unknown   no  
3       may  unknown   no  
4       may  unknown   no  
...     ...      ...  ...  
45206   nov  unknown  yes  
45207   nov  unknown  yes  
45208   nov  success  yes  
45209   nov  unknown   no  
45210   nov    other   no  

[45211 rows x 10 columns]

Kode pertama mengidentifikasi fitur-fitur yang memiliki tipe data kategorikal (misalnya, 'job', 'marital', 'education', dll.) menggunakan dataset.columns dan dataset[feature].dtypes == "O".

In [12]:
for i in categorical_features:
    print(dataset[i].unique())

['management' 'technician' 'entrepreneur' 'blue-collar' 'unknown'
 'retired' 'admin.' 'services' 'self-employed' 'unemployed' 'housemaid'
 'student']
['married' 'single' 'divorced']
['tertiary' 'secondary' 'unknown' 'primary']
['no' 'yes']
['yes' 'no']
['no' 'yes']
['unknown' 'cellular' 'telephone']
['may' 'jun' 'jul' 'aug' 'oct' 'nov' 'dec' 'jan' 'feb' 'mar' 'apr' 'sep']
['unknown' 'failure' 'other' 'success']
['no' 'yes']


identifikasi data unique categorical 

In [14]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()

for feature in categorical_features:
    print(dataset[feature].unique())
    dataset[feature] = label_encoder.fit_transform(dataset[feature])
    print(dataset[feature].unique())

['management' 'technician' 'entrepreneur' 'blue-collar' 'unknown'
 'retired' 'admin.' 'services' 'self-employed' 'unemployed' 'housemaid'
 'student']
[ 4  9  2  1 11  5  0  7  6 10  3  8]
['married' 'single' 'divorced']
[1 2 0]
['tertiary' 'secondary' 'unknown' 'primary']
[2 1 3 0]
['no' 'yes']
[0 1]
['yes' 'no']
[1 0]
['no' 'yes']
[0 1]
['unknown' 'cellular' 'telephone']
[2 0 1]
['may' 'jun' 'jul' 'aug' 'oct' 'nov' 'dec' 'jan' 'feb' 'mar' 'apr' 'sep']
[ 8  6  5  1 10  9  2  4  3  7  0 11]
['unknown' 'failure' 'other' 'success']
[3 0 1 2]
['no' 'yes']
[0 1]


Mengubah data kategorikal menjadi numerik

In [16]:
dataset

age  job  marital  education  default  balance  housing  loan  contact  \
0       58    4        1          2        0     2143        1     0        2   
1       44    9        2          1        0       29        1     0        2   
2       33    2        1          1        0        2        1     1        2   
3       47    1        1          3        0     1506        1     0        2   
4       33   11        2          3        0        1        0     0        2   
...    ...  ...      ...        ...      ...      ...      ...   ...      ...   
45206   51    9        1          2        0      825        0     0        0   
45207   71    5        0          0        0     1729        0     0        0   
45208   72    5        1          1        0     5715        0     0        0   
45209   57    1        1          1        0      668        0     0        1   
45210   37    2        1          1        0     2971        0     0        0   

       day  month  duration  campaign  pdays  previous  poutcome  y  
0        5      8       261         1     -1         0         3  0  
1        5      8       151         1     -1         0         3  0  
2        5      8        76         1     -1         0         3  0  
3        5      8        92         1     -1         0         3  0  
4        5      8       198         1     -1         0         3  0  
...    ...    ...       ...       ...    ...       ...       ... ..  
45206   17      9       977         3     -1         0         3  1  
45207   17      9       456         2     -1         0         3  1  
45208   17      9      1127         5    184         3         2  1  
45209   17      9       508         4     -1         0         3  0  
45210   17      9       361         2    188        11         1  0  

[45211 rows x 17 columns]

menampilkan hasil pergantian data 

In [18]:
x = dataset.drop(['y', 'age'], axis = 1)
y = dataset['y']

Kolom 'y' (target) dan 'age' dihapus dari dataset untuk memisahkan fitur (X) dan target (y). Hal ini dilakukan untuk mempersiapkan data agar bisa digunakan dalam pelatihan model

In [22]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.25,random_state = 42) 

Data dibagi menjadi set pelatihan dan set pengujian menggunakan train_test_split dengan proporsi 75% untuk pelatihan dan 25% untuk pengujian. Pembagian ini penting untuk memastikan bahwa model dapat diuji dengan data yang belum pernah dilihat sebelumnya.

In [24]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(x_train, y_train)

GaussianNB()

Model yang digunakan dalam kode ini adalah GaussianNB dari sklearn.naive_bayes. Model ini bekerja dengan prinsip Naive Bayes, yang merupakan metode probabilistik untuk klasifikasi.

In [26]:
y_pred_train = model.predict(x_train)
y_pred_test = model.predict(x_test)

Pengujian model dilakukan dengan menggunakan data pengujian (x_test) yang telah dibagi sebelumnya. Model melakukan prediksi pada data ini dengan menggunakan model.predict(x_test). Hasil prediksi kemudian dievaluasi menggunakan matriks kebingungan dan laporan klasifikasi untuk menilai performa model pada data yang tidak terlihat.

In [30]:
model.n_features_in_

15

In [32]:
x_baru = np.array([[35, 1, 1, 2, 0, 1200, 1, 0, 0, 5, 8, 300, 2, 30, 3]])
y_pred_baru = model.predict(x_baru)
y_pred_baru

/opt/anaconda3/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(


array([0])

In [34]:
from sklearn.metrics import confusion_matrix, classification_report
print('evaluasi training')
print(confusion_matrix(y_train, y_pred_train))
print(classification_report(y_train, y_pred_train))

print('evaluasi testing')
print(confusion_matrix(y_test, y_pred_test))
print(classification_report(y_test, y_pred_test))

evaluasi training
[[26634  3338]
 [ 2222  1714]]
              precision    recall  f1-score   support

           0       0.92      0.89      0.91     29972
           1       0.34      0.44      0.38      3936

    accuracy                           0.84     33908
   macro avg       0.63      0.66      0.64     33908
weighted avg       0.86      0.84      0.84     33908

evaluasi testing
[[8785 1165]
 [ 766  587]]
              precision    recall  f1-score   support

           0       0.92      0.88      0.90      9950
           1       0.34      0.43      0.38      1353

    accuracy                           0.83     11303
   macro avg       0.63      0.66      0.64     11303
weighted avg       0.85      0.83      0.84     11303



Analisis akurasi model dilakukan dengan menggunakan Confussion Matrix dan clasification report